/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'qxue' at '6/20/16 8:54 PM' with Gradle 2.3
 *
 * @author qxue, @date 6/20/16 8:54 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
